#!/usr/bin/sh
#A wrapper script for the workaround a bug with non-latin characters contained in the CAD file name and path.
if [[ -f ${1} ]];then
   FULLFILEPATH=$(cd $(dirname ${1}) && pwd)/$(basename ${1})
   FILEHASH=$(md5sum ${FULLFILEPATH} | cut -f1 -d" " | cut -c1-8)
   mkdir -p /tmp/DraftSight_$(whoami)_temp/${FILEHASH}
   ln -s ${FULLFILEPATH} /tmp/DraftSight_$(whoami)_temp/${FILEHASH}/${FILEHASH}.${FULLFILEPATH##*.}
   pushd /tmp/DraftSight_$(whoami)_temp/${FILEHASH}
   /opt/dassault-systemes/DraftSight/Linux/DraftSight ${FILEHASH}.${FULLFILEPATH##*.}
   popd
   if [ /tmp/DraftSight_$(whoami)_temp/${FILEHASH}/ ]; then
      rm -rf /tmp/DraftSight_$(whoami)_temp/${FILEHASH}
   fi
   
   else
   /opt/dassault-systemes/DraftSight/Linux/DraftSight ${1}
fi
